"use client";

import { useState } from "react";
import { Avatar } from "@/components/ui";

export default function SettingsPage() {
  const [saved, setSaved] = useState(false);
  return <div className="mx-auto max-w-4xl p-5 md:p-9"><p className="text-sm text-slate-500">Sua conta e preferências</p><h1 className="mt-1 text-2xl font-bold md:text-3xl">Perfil e configurações</h1><section className="mt-7 rounded-2xl border border-slate-100 bg-white p-6 shadow-card"><div className="flex items-center gap-4 border-b border-slate-100 pb-6"><Avatar initials="MC" color="bg-orange-400" /><div><h2 className="font-bold">Marina Costa</h2><p className="text-sm text-slate-500">Administradora · Aurora Studio</p></div><button className="ml-auto rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold">Alterar foto</button></div><div className="mt-6"><h2 className="font-bold">Dados da conta</h2><p className="mt-1 text-sm text-slate-500">Informações visíveis para os membros do workspace.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Nome completo<input defaultValue="Marina Costa" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-brand-400" /></label><label className="text-xs font-semibold text-slate-600">E-mail<input type="email" defaultValue="marina@aurorastudio.com" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-brand-400" /></label><label className="text-xs font-semibold text-slate-600 sm:col-span-2">Cargo<input defaultValue="Product Designer & Administradora" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-brand-400" /></label></div><div className="mt-7 flex items-center justify-between border-t border-slate-100 pt-5"><span className="text-xs text-emerald-600">{saved ? "Alterações salvas com sucesso." : ""}</span><button onClick={() => setSaved(true)} className="rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white">Salvar alterações</button></div></section></div>;
}
